ktor:
    application:
        modules:
            - com.muriloorias.ApplicationKt.module
    deployment:
        port: 8080
    database:
        url: "jdbc:h2:file:./build/db"
        driver: "org.h2.Driver"
        maximumPoolSize: 10